import { CAPABILITY_KINDS } from "../capabilities/index.js";
import type { ServerDefinition } from "../schema.js";

/** Versions pinned into every generated project, kept in one place. */
const PINNED = {
  sdk: "^1.29.0",
  zod: "^3.25.76",
  types_node: "^22.10.5",
  typescript: "^5.7.3",
  vitest: "^2.1.8",
} as const;

export function renderPackageJson(def: ServerDefinition): string {
  const pkg = {
    name: def.name,
    version: def.version,
    private: true,
    type: "module",
    description: def.description ?? `${def.name} MCP server`,
    scripts: {
      build: "tsc",
      start: "node dist/index.js",
      dev: "tsc --watch",
      inspect: "npm run build && npx @modelcontextprotocol/inspector node dist/index.js",
      test: "vitest run",
    },
    dependencies: {
      "@modelcontextprotocol/sdk": PINNED.sdk,
      zod: PINNED.zod,
    },
    devDependencies: {
      "@types/node": PINNED.types_node,
      typescript: PINNED.typescript,
      vitest: PINNED.vitest,
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function renderTsConfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      outDir: "dist",
      rootDir: "src",
      strict: true,
      noUncheckedIndexedAccess: true,
      declaration: false,
      sourceMap: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      verbatimModuleSyntax: true,
    },
    include: ["src/**/*.ts"],
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

export function renderVitestConfig(): string {
  return `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["test/**/*.test.ts"],
  },
});
`;
}

export function renderGitignore(): string {
  return ["node_modules/", "dist/", "*.tsbuildinfo", "*.log", ".DS_Store", ""].join("\n");
}

export function renderReadme(def: ServerDefinition): string {
  const claudeConfig = JSON.stringify(
    {
      mcpServers: {
        [def.name]: {
          command: "node",
          args: [`/ABSOLUTE/PATH/TO/${def.name}/dist/index.js`],
        },
      },
    },
    null,
    2,
  );

  return `# ${def.name}

${def.description ?? "An MCP server generated with [mcp-builder](https://github.com/hillzeealex/mcp-builder)."}

> Generated by mcp-builder. Edit the handler stubs in \`src/\` to implement your logic.

## Capabilities

${renderCapabilityTable(def)}

## Getting started

\`\`\`bash
npm install
npm run build
npm start
\`\`\`

Implement your logic by filling in the \`TODO\` handlers under \`src/tools\`, \`src/resources\`, and \`src/prompts\`.

## Inspect locally

The [MCP Inspector](https://github.com/modelcontextprotocol/inspector) is the fastest way to exercise your server:

\`\`\`bash
npm run inspect
\`\`\`

## Connect to Claude Desktop

${
  def.transport === "stdio"
    ? `Build the server, then add it to \`claude_desktop_config.json\` (use an **absolute** path):

\`\`\`json
${claudeConfig}
\`\`\`

Restart Claude Desktop. The server's tools, resources, and prompts will appear in the client.`
    : "This server uses the **Streamable HTTP** transport. Start it with `npm start` (listens on `http://localhost:3000/mcp`), then point an HTTP-capable MCP client at that URL."
}

## Tests

\`\`\`bash
npm test
\`\`\`
`;
}

function renderCapabilityTable(def: ServerDefinition): string {
  const rows = [
    "| Kind | Name | Description |",
    "| --- | --- | --- |",
    ...CAPABILITY_KINDS.flatMap((kind) => kind.readmeRows(def)),
  ];
  return rows.join("\n");
}
